### ISSUE TITLE
lua

### ISSUE THREAD

**Issue by AlexFundorin** [Erriez/reaper_csurf_vs2015#1]
Not really an issue, but a request.
Can you strip this down, so it would compile for only one surface and with a different name than an original version? Is it possible to integrate LUA to have a similar experience as when writing reascripts for Reaper, but actually programming a csurf plugin instead?

**Comment by Erriez** [comment]
Hi Alex,

> Can you strip this down, so it would compile for only one surface and with a different name than an original version?

I've created a feature branch which supports only one CSurface, based on the easiest BCF2000 as starting point:

git clone -b Feature/SingleCSurf https://github.com/Erriez/reaper_csurf_vs201x.git

> Is it possible to integrate LUA to have a similar experience as when writing reascripts for Reaper, but actually programming a csurf plugin instead?

Reaper's build-in LUA cannot access all MIDI ports which is the main limitation. I suggest you to ask people on the Reaper forum to add LUA inside this CSurf project.

Success!

**Comment by AlexFundorin** [comment]
Great! Thanks alot.
  
I can DL branch via github plugin into VS, but there's no solution for a branch. What's the proper way of compiling a plugin from a github branch?

**Comment by Erriez** [comment]
The easiest way is to install a Git Client on Windows and open a command prompt. Then type:
```git clone -b Feature/SingleCSurf https://github.com/Erriez/reaper_csurf_vs201x.git```

Now open Builds\VisualStudio2015\reaper_csurf.sln with Visual Studio 2015. (I did not update the other solutions)

In the Microsoft Visual Studio lower right corner you'll find a Git menu which contains the master branch and the new Feature/SingleCSurf branch which should be activated. Then follow the Reaper SDK installation instructions in the README.md and you should be able to build the single CSurf project.

**Comment by AlexFundorin** [comment]
Hi. I'm doing good with plugin coding, thanks to you. I'm using single project fork as a base. 
The thing is that only debug build is working (both in debugger mode and standalone). It's size is >1mb, while release is <90kb. Tried inspecting project properties to find out, why is it happening, but couldn't find the reason. 
Do you have any clue, what is happening here?

UPD.
The same thing happens with the master branch (also VS15).

**Comment by Erriez** [comment]
Yes, the initial debug version is 989KB and release version is 29KB.
I suggest you to double check if the release DLL is copied correctly to the Reaper Plugins directory.

1. Right mouse click reaper_csurf in the Solution Explorer > Properties
2. Select Configuration: Debug
3. Expand Configuration Properties | Build Events | Post-Build Event | Command Line
4. Compare the settings with Configuration: Release

What do you mean with "not working?".

**Comment by AlexFundorin** [comment]
It's not about copying, actually. I can copy DLLs to UserPlugins folder myself, if needed. They're copying automatically, though.
I can't check if master branch is working properly, since I don't have any of the included controllers, but my own project is working with >1mb debug version, but not with <90kb release version of the library. If I remember correctly, this was true from the very moment I started modifying mydevice branch to make it work with my controller. Debug version always worked, but not the release one. Both release and debug versions are compiling fine (for my project, master branch and mydevice branch), except those "deprecated" warnings.
https://i.imgur.com/Jc03r0Y.png

Release version can light up LEDs on the controller, but doesn't receive any data from Reaper, as it seems.

**Comment by Erriez** [comment]
Is the MIDI port displayed correctly in your surface dialog box?
(In Reaper open Options | Preferences | Control/OSC/web)

I also suggest you to check the MIDI port settings in REAPER.ini section csurf_0=MyDevice 0 9 -1 -1 and compare this with the debug and release version after changing the MIDI in/out ports.

I'm also thinking about preprocessor differences or compilation settings in the C/C++ tab.

Is a breakpoint reached on OnMIDIEvent() in debug and release mode?

**Comment by AlexFundorin** [comment]
Breakpoints are successfully reaching with all SetSurfaceSolo() type methods, which are called upon changes in Reaper, which means that Reaper can communicate with release.
"Run() if (midi_in)" is also reached, as well as OnMIDIEvent() (shot: https://i.imgur.com/aOWQAnu.png)

reaper.ini release:
csurf_cnt=1
csurf_0=NovationSL 0 9 55 57

reaper.ini debug:
csurf_cnt=1
csurf_0=NovationSL 0 9 55 57

Preprocessor definitions are the same (except warnings suppression in debug).

Optimization: 
r: https://i.imgur.com/RZI1z5s.png
d: https://i.imgur.com/lBvLD7U.png

Code generation:
r: https://i.imgur.com/fIOy9Fz.png
d: https://i.imgur.com/8C2ZjBc.png

Everything else is the same, except output dirs.

Port is displayed correctly (ini data as proof).

**Comment by Erriez** [comment]
What happens if you change the code generation settings in the release version with the settings of the debug? I remember some problems with this earlier. The optimization settings are correct.
Removing all output build directories may help to rebuild everything.
Do you see build warnings which are ignored accidentally?

**Comment by AlexFundorin** [comment]
There are no other build warnings except those that can be suppressed: http://pastebin.ru/dkhYQvMJ
I've tried removing build directories completely.
I'm currently experimenting with code generation settings (new area to me).
For now, I can tell you that changing some of the code generation settings to those that are set in debug isn't possible, because of optimization settings.
I'll try disabling optimization, then setting code generation as in debug. If this will make release to work, I'll then try reverting those changes, step by step.

**Comment by AlexFundorin** [comment]
Changing Runtime library from Multi-threaded DLL to either Multi-threaded Debug or Multi-threaded Debug DLL, made release to work.
Should I leave like that?

**Comment by Erriez** [comment]
I remember the same problem for another CSurf project. 
Yes, that seems to be the workaround. It results in a slightly larger DLL.

I found a similar issue on the Reaper forum with the same solution:
https://forum.cockos.com/showpost.php?s=03aae36d8c3f47009f500e789efe62eb&p=270629&postcount=9

Nice work, Alex!

**Comment by AlexFundorin** [comment]
Thanks for help.
Any news about reaper-csurf-juce-template? 
I'm also thinking about adding some GFX framework to make a realtime config/cheatsheet popup window for my project.

**Comment by Erriez** [comment]
At the moment I've no plans to implement a Juce interface, because I switched to a simple win32 interface.

Success with your development!

**Comment by AlexFundorin** [comment]
Do you have an example of your implementation? What were your reasons to ditch JUCE?

**Comment by Erriez** [comment]
My test applicaiton does not work anymore after a Juce upgrade. Now it complains about memory leaks at run-time.
My idea was to create simple dialogs to configure the CSurf DLL and change some device settings. I switched to win32 GUI's, so I don't use Juce anymore.

**Comment by AlexFundorin** [comment]
That's my idea, also. What surface are you using, BTW?

I've compiled x86 version of the plugin for my friend, who owns the same controller, and hid Reaper couldn't see the plugin. I've installed portable x86 version on my pc and it also couldn't see the plugin.
Then, I've compiled early version of my mydevice "fork", and it was seen by x86 Reaper. After a bit of investigating, I came to conclusion, that this might've happened because I've replaced original reaper_plugin.h file from 2009 with more recent 2014 version. Still struggling to find out the particular cause, though.
What reaper_plugin/reaper_plugin_functions headers and WDL sources are you using in your project? The original ones or something newer?

**Comment by Erriez** [comment]
I'm surprised that 32-bit version is still used. 32-bit support will be dropped with next Windows version. I considered to completely remove 32-bit support, but decided to keep it. I did not update the 32-bit build  settings in the SingleCSurf branch, so I can imagine that something is missing.

I've ported the original SDK from http://reaper.fm/sdk/plugin/plugin.php:
http://reaper.fm/sdk/plugin/reaper_extension_sdk.zip (last updated December 16 2009)

You can generate your own reaper_plugin_functions.h include file from Reaper by opening the Actions window | Type in the filter box: developer | Double click [developer] Write C++ API functions header.

You can use the Sysinternals tool to see which DLL's are loaded in Reaper, as well as displaying all search paths:
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon
I think the behavior of the plugin-path in the Reaper portable version may be different.

Success!

**Comment by Erriez** [comment]
Is this Juce thread helpful for you?
https://forum.cockos.com/showthread.php?t=188350

**Comment by AlexFundorin** [comment]
Yes,  the thread is helpful. Thanks.
As for 32 bit version, I'm already using reaper_plugin_functions.h that is generated by Reaper. I've also modified reaper_plugin.h, so that it would automatically import all available functions from this header, instead of adding them manually with IMPAPI. It works fine with x64 version, but seems to cause trouble with x86 version. 
As for 32 bit support, my friend is 60+ years old and he doesn't want to upgrade W7 on his laptop. 🤡

**Comment by AlexFundorin** [comment]
This is what I get in the procmon: https://i.imgur.com/vbsLucW.png
